version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: p4ssw0rd
      POSTGRES_USER: gymuser
      POSTGRES_DB: gympass
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
