version: "3"
services:
  app:
    # Utilizando build da imagem criada localmente via comando docker build -t teste-gympass:1.0.0 .
    # image: teste-gympass:1.0.0

    # Utilizando arquivo Dockerfile para realizar o build ao executar o comando docker-compose up
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 3001:3000
    environment:
      - DATABASE_URL=postgresql://gymuser:p4ssw0rd@db:5432/gympass?schema=public
      - NODE_ENV=production
    
    
    networks:
      - gympass-network

    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: p4ssw0rd
      POSTGRES_USER: gymuser
      POSTGRES_DB: gympass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    
    networks:
      - gympass-network

volumes:
  postgres_data:

networks:
  gympass-network:
    driver: bridge
  

